### ISSUE TITLE
A couple stylistic changes/fixes to explore

### ISSUE THREAD

**Issue by mrueschman** [pmanko/www.myapnea.org#13]
None of these are mandates, just things to consider/try that came to mind:
- On FAQ, reverse the border effect on the tabs? It feels to me like the one selected is the least prominent in the tab display, so I wondered if reversing would feel more natural.
- Alignment for sections does not seem precise. When clicking on the right-hand section/subsection navigation the anchors do not seem to land at the correct spots on the page.
- Make spacing at top of pages consistent (for instance, Team and FAQ pages are out of alignment with the page titles currently)

**Comment by pmanko** [comment]
Moved the second bullet point to #14
